apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth-light
  template:
    metadata:
      labels:
        app: eth-light
    spec:
      containers:
      - name: geth
        image: ethereum/client-go
        args: ["--syncmode", "light", "--http", "--http.addr", "0.0.0.0", "--http.api", "eth,web3,net"]
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: eth-light-svc
spec:
  type: LoadBalancer
  selector:
    app: eth-light
  ports:
  - port: 8545
    targetPort: 8545
