apiVersion: apps/v1
kind: Deployment
metadata:
  name: indy-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indy-node
  template:
    metadata:
      labels:
        app: indy-node
    spec:
      containers:
      - name: indy
        image: hyperledger/indy-node:latest
        ports:
        - containerPort: 9701
        - containerPort: 9702
---
apiVersion: v1
kind: Service
metadata:
  name: indy-svc
spec:
  type: LoadBalancer
  selector:
    app: indy-node
  ports:
  - port: 9701
    targetPort: 9701
  - port: 9702
    targetPort: 9702
